services:
  - type: web
    name: sistema-receitas-culinarias
    env: node
    buildCommand: npm install && npm run migrate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: sistema-receitas-culinarias
          property: port
      - key: DB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: "*"
      - key: API_URL
        fromService:
          type: web
          name: sistema-receitas-culinarias
          property: host

